meta_title: "Women On Rails"
meta_description: "Femmes debutantes intermediaires, rejoignez-nous tous les lundis pour apprendre à coder et progresser ensemble avec Ruby on Rails"
meta_image: "meta-image.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@womenonrails" #indispensable pour les Twitter Cards
